language: python
python:
- '3.6'
install:
- pip install -r test_requirements.txt
script: pytest
env:
- FLASK_CONFIG=config.TestConfig
deploy:
  provider: cloudfoundry
  api: https://api.cloud.service.gov.uk
  username: adam.shimali@gmail.com
  password:
    secure: 7pZuy8lQLrBOmQytLMGgwK0TtMvK9lOhdbMFp0cJEWHAuVhtPOo8grkKIFQ22j5zFEUfiX438QuEF7wKxOwPHrFuWl6PM/N+bkZSpEgA9gXiaW/431+u6T82PwttJW3l+h5qyhPSNeJvC9CATF6sm6XQ17/FQA37XL/tZjV8lgnYRLBcijirdPyr+e6gCuJURtEkZf1E2aYEq3TH5P7eF8y2R37d+FWHl5jRg+R8x4gcEI0c7wvaBSNCOaM/1Ax0xvE+HJUrEQTu6ur95oMVC36hgYnoWGG4OmlTjHA3qdR3IXQSTCQAKlyozw4vQdOgSS7PgMlBsklNMsKlre5SpwvlwF4jW2VJxod1ViPjzZ0hsA1YXh6vHR3y22z9a4EIqmIobahkAt0WhzpFG8GIETG5sbfy0+iW9Zzfaa0iYybm2IlU+CROZli0zJobG2fMzFXuIue7cA45olZJ6OejZi2rAy4u7cracz2p16MTKxRVpqpa3kSy5eTiRiSSCoPwZoy07c33ZWfWhnJ6GNAzcSbm0PMdeWyZCJXolL7DSlZZf8itQw5Oyw0VmJ9h/CHga7RNCEL6MYNpEtNLCDi4gQdlPfjg122Wdx2l3O4j+LTcCRfZjxAJbdWahqx75xofLDn0541NcIGIiu70Chsq7O41HgVR+qly6axILPur9m0=
  organization: mhclg-digital-land
  space: digital-land
  on:
    repo: communitiesuk/digital-land-explorer

